### ISSUE TITLE
OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

### ISSUE THREAD

**Issue by joncasdam** [resulto-admin/django-celery-fulldbresult#28]
When running migration, with Django 2.0 got this traceback
```
venv/lib64/python3.6/site-packages/MySQLdb/connections.py", line 292, in query
mysql.connection.query(self, query)
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
Applying django_celery_fulldbresult.0001_initial...
```

Django==2.0
celery==3.1.25
django-celery==3.2.2
django-celery-fulldbresult==0.5.3

**Comment by joncasdam** [comment]
is it related to https://github.com/celery/django-celery-beat/issues/18 ?

**Comment by bartdag** [comment]
Thanks for raising the issue!

I will discuss with my team what to do about it and your pull request.

I see that django, django-celery-beat and django-celery have not blessed a solution for that problem yet so I am hesitant to go ahead and just decrease the size of fields. This is usually a no go because it is not backward compatible (large existing values can prevent the migration).

I am particularly worried about the hosname and task name because these can get quite large.

Exchange, task id and routing key should be fine but who knows: we are not heavy users of routing key and exchange so it's difficult to comment.

Overall, I'm afraid that to help mysql users with utf8mb4, we will break the environment of other users.

On a side note, we are moving to support celery 4 and I believe we will remove all traces of PeriodicTask and the like from our code because django-celery-beat has now added the features we were missing. On the other hand, we will still heavily extend django-celery-results so this issue may come up again.

**Comment by joncasdam** [comment]
I see. I wasn't that confident and opening the pull request because I agree with your remarks. 
In my case that was brought up due to a work demand, thus being prone to be changed, but indeed it would be something worthy of a discussion.

**Comment by joncasdam** [comment]
I'm closing the pull request for now.

**Comment by joncasdam** [comment]
Also, I'm going to close the issue, since it's not really an issue of this library.
I decided to keep my database using `utf8` and, when needed, I'll add a `migration` defining `charset` as `utf8mb4`.
Thanks for the support.
